import 'package:flutter/material.dart';
import '../exercises/exercise.dart';
class EditorScreen extends StatefulWidget { final Exercise exercise; const EditorScreen({super.key, required this.exercise}); @override State<EditorScreen> createState() => _EditorScreenState(); }
class _EditorScreenState extends State<EditorScreen> {
  late final TextEditingController controller; String output = 'Console ready.';
  @override void initState(){super.initState(); controller = TextEditingController(text: widget.exercise.code);}
  @override void dispose(){controller.dispose(); super.dispose();}
  void run(){final s=controller.text; final b='{' .allMatches(s).length - '}'.allMatches(s).length; final p='('.allMatches(s).length - ')'.allMatches(s).length; setState(() { output = b != 0 || p != 0 ? 'Source structure error\nBraces delta: $b\nParentheses delta: $p' : 'Source validated.\nLanguage: ${widget.exercise.language}\nLines: ${s.split('\n').length}\n\nThe real runtime bridge will execute this source when the pinned engine is bundled.'; });}
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Text(widget.exercise.title), actions: [FilledButton.icon(onPressed: run, icon: const Icon(Icons.play_arrow), label: const Text('Run')), const SizedBox(width: 8)]), body: Column(children: [Expanded(child: Padding(padding: const EdgeInsets.all(12), child: TextField(controller: controller, expands: true, maxLines: null, minLines: null, style: const TextStyle(fontFamily: 'monospace', fontSize: 14), decoration: const InputDecoration(labelText: 'Source', alignLabelWithHint: true)))), const Divider(height: 1), Material(color: Theme.of(context).colorScheme.surfaceContainerHighest, child: Padding(padding: const EdgeInsets.fromLTRB(16,10,16,6), child: Row(children: [const Icon(Icons.terminal,size:18), const SizedBox(width:8), Text('Console',style:Theme.of(context).textTheme.titleMedium), const Spacer(), TextButton(onPressed:()=>setState(()=>output=''),child:const Text('Clear'))]))), Container(width:double.infinity,height:150,padding:const EdgeInsets.all(16),color:const Color(0xFF08090B),child:SingleChildScrollView(child:Text(output,style:const TextStyle(color:Color(0xFFE1E4EA),fontFamily:'monospace',fontSize:12))))]));
}
